### ISSUE TITLE
Closed-loop Linkage Representation in URDF and Issac Gym

### ISSUE THREAD

**Issue by Cfather** [generalroboticslab/legged_env#1]
Hi, may I ask how you represent the closed-loop linkages on the knee and the ankle in your URDF and Issac Gym?

**Comment by boxiXia** [comment]
We did not use closed-loop linkages because Isaacgym does not natively support it. However, we did attempt to set up the close-loop linkage as [this paper](https://arxiv.org/pdf/2303.03381) suggests, but we did not get a better result as compared to open loop linkage. If you are interested, check out our [previous implementation with passive joints](https://github.com/generalroboticslab/legged_env/blob/0e946cf3eabaf39cdbe92cb6d73c8f47742e0ed6/envs/tasks/legged_terrain.py#L2025)
